// Auto-generated by ATShogi-OM Extreme Host 16-Core Saturation Generator
// Total Games: 10000, Parallel Threads: 16, Saturated: True
#ifndef ATSHOGI_GENERATED_STATIC_JOSEKI_H
#define ATSHOGI_GENERATED_STATIC_JOSEKI_H

#include <stdint.h>

static const float g_selfplay_static_joseki[81] = {
    // 1筋: 1a..1i
       -4.75f,    +5.20f,   +29.74f,   -10.98f,   +17.04f,    +6.65f,    -0.69f,    +3.38f,   +19.42f, 
    // 2筋: 2a..2i
      -15.54f,   +22.57f,   -78.04f,   -37.06f,    -0.72f,   +78.11f,    +0.95f,    -9.43f,   -10.34f, 
    // 3筋: 3a..3i
       +9.28f,    -1.43f,   -52.75f,   +40.22f,    +1.95f,    -4.06f,   +14.13f,    +0.19f,    +0.40f, 
    // 4筋: 4a..4i
       -2.41f,   -14.09f,   -26.90f,   -29.22f,    -1.83f,   -23.27f,   -16.93f,   -18.76f,    -0.03f, 
    // 5筋: 5a..5i
      -10.22f,    +0.06f,   +10.32f,    +0.21f,   +53.98f,    -0.08f,   +10.14f,    -0.26f,    +6.58f, 
    // 6筋: 6a..6i
       +0.00f,    -0.03f,    +0.00f,   -58.08f,    +0.07f,   +47.32f,    -0.01f,   -20.93f,    +0.00f, 
    // 7筋: 7a..7i
      -12.93f,    +0.18f,   -46.72f,    -0.57f,    -0.33f,   +98.00f,   -13.08f,   +64.21f,    -3.74f, 
    // 8筋: 8a..8i
       -0.07f,    -4.25f,    -0.02f,   -86.43f,    -3.96f,   +40.88f,    +0.19f,   -45.85f,    -2.76f, 
    // 9筋: 9a..9i
      -31.31f,    -0.04f,    +1.12f,    -0.24f,   -14.38f,    +5.84f,    -0.02f,    -0.01f,    +0.73f
};

#endif // ATSHOGI_GENERATED_STATIC_JOSEKI_H
